version: '3.8'

services:
  # MOTOR DEL BACKEND (Node.js/Daniela)
  app:
    build: .
    container_name: soto_system_app
    restart: always
    environment:
      - TZ=America/Caracas
      # Conexión directa a la base de datos usando el nombre del contenedor
      - postgres://user:pass@db-apio-v2:5432/soto_db
      - NODE_ENV=production
      # INYECCIÓN DIRECTA DE LA API KEY (Para que Daniela despierte ya)
      - GOOGLE_API_KEY=AIzaSyBiCiy4j2poFU4RNG7b5gblzIs-u4MW1hQ
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  # TANQUE DE GASOLINA (Base de Datos PostgreSQL)
  db:
    image: postgres:15
    container_name: soto_system_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=soto_db
      - TZ=America/Caracas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
