# Generated by Django 6.0.4 on 2026-04-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_irritacion', models.IntegerField(default=0)),
                ('autoesteem', models.IntegerField(default=50)),
                ('nivel_dopamina', models.IntegerField(default=50)),
                ('ultima_conexion_gabriel', models.DateTimeField(auto_now=True)),
                ('modo_actual', models.CharField(default='normal', max_length=50)),
                ('dia_del_ciclo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('tag', models.CharField(choices=[('general', 'General'), ('comida', 'Comida/Dieta'), ('familia', 'Familia/Primos'), ('musica_vallenato', 'Vallenato Sabroso'), ('musica_rock', 'Rock/Retro'), ('humor_negro', 'Humor Negro/Chistes Internos'), ('hormonal_picara', 'Modo Hormonal/Pícara'), ('celos_humor', 'Celosa-Chistosa'), ('protectora_sargento', 'Sargento/Líder'), ('negocios_saas', 'Soto System/SaaS')], default='general', max_length=50)),
                ('es_importante', models.BooleanField(default=False)),
                ('impacto_emocional', models.IntegerField(default=5)),
            ],
        ),
    ]
