# Generated by Django 6.0.4 on 2026-05-26 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoemocional',
            old_name='autoesteem',
            new_name='autoestima',
        ),
        migrations.AlterField(
            model_name='estadoemocional',
            name='ultima_conexion_gabriel',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
