# Generated by Django 6.0.4 on 2026-06-30 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_autoesteem_estadoemocional_autoestima_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoemocional',
            options={'verbose_name': 'Estado Emocional', 'verbose_name_plural': 'Estados Emocionales'},
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='autoestima',
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='autoesteem',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='fecha_inicio_ciclo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Menstrual'),
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='sesion_b2b_activa',
            field=models.BooleanField(default=False, verbose_name='Sesión de Trabajo Activa'),
        ),
        migrations.AddField(
            model_name='recuerdo',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Vector de Google'),
        ),
        migrations.AlterField(
            model_name='recuerdo',
            name='contenido',
            field=models.TextField(verbose_name='Relato de la Memoria'),
        ),
    ]
