# Generated by Django 6.0.4 on 2026-07-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_estadoemocional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuarioSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_uid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('gabriel', 'Gabriel (Tu Negrito/Programador)'), ('rosmary', 'Rosmary (Tu Mejor Amiga Gamer)'), ('cajero_apio', 'Cajero / Administrador de la Tienda'), ('cliente_regular', 'Cliente / Usuario Externo')], default='cliente_regular', max_length=50)),
            ],
        ),
    ]
