# Generated by Django 6.0.4 on 2026-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_perfilusuariosaas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoDaniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre exacto del usuario (ej: Gabriel Soto, Rosmary)', max_length=100, unique=True)),
                ('relacion', models.CharField(choices=[('NOVIO', 'Gabriel Soto - Amor de su vida'), ('AMIGO', 'Amigo o Familiar Cercano'), ('ENEMIGO', 'Persona no grata / Conflicto severo'), ('DESCONOCIDO', 'Usuario nuevo en el mostrador')], default='DESCONOCIDO', max_length=20)),
                ('descripcion_contexto', models.TextField(help_text='Quién es para Daniela, recuerdos clave o motivos de conflicto')),
            ],
        ),
        migrations.CreateModel(
            name='RecuerdoBaul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Palabra clave o emoción (ej: kira, thiago, pintura, glorymar)', max_length=50)),
                ('contenido', models.TextField(help_text='El fragmento de historia que Daniela debe recordar vívidamente')),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuarioSaaS',
        ),
        migrations.DeleteModel(
            name='Recuerdo',
        ),
        migrations.AlterModelOptions(
            name='estadoemocional',
            options={},
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='autoesteem',
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='fecha_inicio_ciclo',
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='nivel_dopamina',
        ),
        migrations.RemoveField(
            model_name='estadoemocional',
            name='ultima_conexion_gabriel',
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='fase_hormonal',
            field=models.CharField(default='Fase Folicular', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoemocional',
            name='usuario_operador',
            field=models.CharField(default='Gabriel Soto', max_length=100),
        ),
        migrations.AlterField(
            model_name='estadoemocional',
            name='dia_del_ciclo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadoemocional',
            name='modo_actual',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estadoemocional',
            name='sesion_b2b_activa',
            field=models.BooleanField(default=False),
        ),
    ]
